name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}.
   .        run: | 
   git push https://huggingface.co/spaces/Lavanmawlood/lavlab-chemical-portal main --force
